name: recurrent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - absl-py=0.11.0
  - aiohttp=3.7.3
  - astor=0.8.1
  - async-timeout=3.0.1
  - atari_py=0.2.6
  - attrs=20.3.0
  - blas=2.20
  - blinker=1.4
  - blosc=1.20.1
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.11.8
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.3.0
  - cryptography=3.2.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.6
  - decorator=4.4.2
  - expat=2.2.9
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.10.4
  - future=0.18.2
  - gast=0.2.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.3
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.33.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gym=0.17.3
  - gym-atari=0.17.3
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=3.1.0
  - jasper=2.0.14
  - joblib=0.17.0
  - jpeg=9d
  - jxrlib=1.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - lerc=2.2
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libglu=9.0.0
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm10=10.0.1
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - libzopfli=1.0.3
  - llvm-openmp=11.0.0
  - llvmlite=0.34.0
  - lz4-c=1.9.2
  - markdown=3.3.3
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mkl=2020.4
  - multidict=4.7.5
  - ncurses=6.2
  - networkx=2.5
  - ninja=1.10.1
  - numba=0.51.2
  - numpy=1.19.4
  - oauthlib=3.0.1
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - opt_einsum=3.3.0
  - pandas=1.1.4
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - protobuf=3.13.0.1
  - pthread-stubs=0.4
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyglet=1.5.0
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.7.0
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.4.1
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.33.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.7.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-gpu=2.1.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tifffile=2020.11.18
  - tk=8.6.10
  - toolz=0.11.1
  - torchvision=0.8.1
  - tornado=6.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zfp=0.5.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - fire==0.3.0
    - gym-retro==0.7.1
    - opencv-contrib-python==4.2.0.34
    - tensorboardx==2.0
    - tensorflow-estimator==2.1.0

